### PR TITLE
Check if signature item move is valid

### LINKED ISSUE #665: Dragging a folder into itself trips an assertion
```
panicked at 'assertion failed: self.ancestors_of(parent).all(|ancestor| ancestor != node)', /build/source/homotopy-common/src/tree.rs:214:9

Stack:

getImports/imports.wbg.__wbg_new_693216e109162396@https://beta.homotopy.io/homotopy_web.js:383:21
console_error_panic_hook::hook::h054793795ecafe17@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[1584]:0x1edd35
core::ops::function::Fn::call::h8bfb3aa716794a98@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[4306]:0x2620b2
std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2617]:0x23f091
std::panicking::begin_panic_handler::{{closure}}::h8e1f8b682ca33009@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3001]:0x250ed6
std::sys_common::backtrace::__rust_end_short_backtrace::h7f7da41799766719@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3906]:0x260cc7
rust_begin_unwind@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3491]:0x25d1d2
core::panicking::panic_fmt::hcdb13a4b2416cf82@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3497]:0x25d33c
core::panicking::panic::ha8ced62e366a0d64@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3438]:0x25c42b
homotopy_common::tree::Tree<T>::reparent_at::h6286dc2e8e72f0ab@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[916]:0x18ead3
homotopy_web::model::proof::signature::Signature::update::h32a767d557c5a6b8@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[392]:0xebb17
homotopy_web::model::proof::ProofState::update::hcbd1af2c53a45541@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[210]:0x293a9
homotopy_web::model::State::update::h22ccd913e54493c1@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[204]:0x113c8
<homotopy_web::app::App as yew::html::component::Component>::update::h2171e0d3465d7692@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[433]:0x1002e5
<yew::html::component::lifecycle::UpdateRunner<COMP> as yew::scheduler::Runnable>::run::h6fa4723e37f68d8e@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[587]:0x13b20d
std::thread::local::LocalKey<T>::with::h37b35463bea3bf1a@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[1933]:0x20f947
yew::scheduler::start::h0bdcb34e20f64b89@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[4305]:0x2620aa
yew::html::component::scope::Scope<COMP>::callback_with_passive::{{closure}}::he7cb63c3f6f077d5@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3049]:0x252921
yew::callback::Callback<IN>::emit::h37ff21f8388a342f@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2644]:0x24082c
yew::callback::Callback<IN>::reform::{{closure}}::hfa457eddde12afbf@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2798]:0x248724
yew::callback::Callback<IN>::emit::h0dcf11516e441fa8@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[1607]:0x1f0489
yew::callback::Callback<IN>::reform::{{closure}}::h6d9fc79d1cb64ed2@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[1088]:0x1ad68f
yew::callback::Callback<IN>::emit::h20610aa22da8781b@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2853]:0x24aff8
yew::callback::Callback<IN>::reform::{{closure}}::h539d28c926e605ab@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3849]:0x2607ac
yew::callback::Callback<IN>::emit::h319462e52e6a7c2f@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2865]:0x24b84b
<yew::html::listener::events::ondrop::Wrapper as yew::virtual_dom::listeners::Listener>::handle::h39c810f1ef2a7e8c@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[4206]:0x261d1f
yew::virtual_dom::listeners::Registry::run_handlers::{{closure}}::hd16248a091840ea4@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[1081]:0x1ac3c3
yew::virtual_dom::listeners::Registry::handle::h8c435928363c8dde@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[1873]:0x20a58b
yew::virtual_dom::listeners::GlobalHandlers::ensure_handled::{{closure}}::{{closure}}::hdafaf758490d7490@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3957]:0x26105a
<dyn core::ops::function::Fn<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h2feab2bf93bb4f7b@https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3750]:0x25fd11
__wbg_adapter_38@https://beta.homotopy.io/homotopy_web.js:262:10
real@https://beta.homotopy.io/homotopy_web.js:229:20
```

### PR DESCRIPTION
**Pull request by thud**
This fixes #665.

### CODE REVIEW

File: homotopy-web/src/model/proof/signature.rs [hunk 1]
```diff
@@ -155,7 +155,11 @@ impl Signature {
                     .push_onto(*node, SignatureItem::Folder("New folder".to_owned(), true));
             }
             SignatureEdit::MoveBefore(from, to) => self.0.reparent_before(*from, *to),
-            SignatureEdit::MoveInto(from, to) => self.0.reparent_under(*from, *to),
+            SignatureEdit::MoveInto(from, to) => {
+                if from != to {
```
Comment (doctorn) [inline homotopy-web/src/model/proof/signature.rs:159]: I think both `MoveBefore` and `MoveInto` should check that `from` is not a transitive parent of `to`. Otherwise, if you move a folder into a sub-folder of itself we'll trip the same assertion etc.

**Review by doctorn — CHANGES_REQUESTED** [review]

File: homotopy-web/src/model/proof/signature.rs (hunk 1 above)
Comment (thud) [reply homotopy-web/src/model/proof/signature.rs:159]: Quite right, good catch. I think this is now fixed.

**Comment by doctorn** [comment]
Awesome -- thanks @thud

**Review by doctorn — APPROVED** [review]
